sudo: false
language: node_js
node_js:
  - "0.12"
  - "iojs"
before_install:
  - phantomjs --version
  - npm install -g grunt-cli
before_script:
  - grunt uglify
  - grunt jst
  - grunt cssmin
  - grunt asset_cachebuster
script: grunt test --verbose --force